### ISSUE TITLE
Sync: Linking with to-many relationships

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#117]
Currently Update Document allows entities to reference existing related entities using "relname" : 123 syntax (additionally "relname_id" : 123 with SenchaAdapter). This works for to-one relationships. Need to add syntax for to-many relationships, which may look like this:

```json
"relname" : [ 1, 2, 3]
```
Operations on the relationship will simply link/unlink the root object, without creating or deleting target objects. More advanced management of relationships is envisioned as a part of another feature - aggregate updates.

**Comment by atomashpolskiy** [comment]
Am I getting it right that you think of combining create/update operation with unrelate operation in this particular case? I'm asking because it contradicts the way create/update with to-one (from entity to parent entity) references works now. Probably it should be left as it is, i.e. specifying multiple references for to-many relationship will result in _adding_ the object for all parent objects, but it will not be removed from any other parent objects that it's currently connected with. What do you think?

**Comment by andrus** [comment]
Yeah, we have 2 options here ("link/unlink" vs "link/ignore unlink") and need to pick one as an implicit default, ignoring the other till the time when we create a more explicit API.

I was considering "link/unlink" as such a default. We discussed with @rzen this tradeoff and figured it will be more practical at the moment. But certainly a more expressive and explicit API is due here eventually.

**Comment by atomashpolskiy** [comment]
Understood, and what about requests with single reference? Should they unlink as well since now or continue to ignore unlink? Two different behaviors for one op may be a bit confusing.

**Comment by andrus** [comment]
Do you mean to-one relationships? Those are semantically different. So "rel":123 means "link" and "rel":null means "unlink".
