### ISSUE TITLE
Implement `start`/`limit` for advanced `include`s

### ISSUE THREAD

**Issue by rzen** [nhl/link-rest#141]
We've come upon infrequent but viable scenarios where its vital to be able to control the number of objects returned by a foreign collection (relationship) in response to an advanced `include`.

**Comment by andrus** [comment]
+1 to add limit to nested collections

**Comment by atomashpolskiy** [comment]
Does this imply limiting fetching from the database as well (almost sure it does, but just to be sure)? We'll need to use separate queries instead of (disjoint) prefetches in that case.

**Comment by rzen** [comment]
Good point, yes it does.

**Comment by atomashpolskiy** [comment]
As far as I can see, this will require major changes - basically rewriting the whole select processing chain. The point is that with database-level offset/limit for nested collections we'll actually have multiple entities instead of a single "resource" entity that we have now; we'll need to manually assemble the resulting DataObject, which is currently assembled by Cayenne; also we'll need to apply sorting in LR instead of leveraging database sort.

**Comment by rzen** [comment]
yikes.. i see.

lets try a less radical option first. if we ever come up on a need to `limit` a huge foreign collection we can revisit.
