### ISSUE TITLE
Support for Java 8 date time types in the metadata requests

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#222]
I have the following meta endpoint (completely vanilla actually):

```java
   @GET
    @Path("meta")
    public MetadataResponse<ContentModule> getMetadata(@Context UriInfo uri) {
        return LinkRest.metadata(ContentModule.class, configuration)
                      .forResource(ContentModuleApi.class)
                      .uri(uri).process();
    }
``` 

For entity attributes of type LocalDateTime, the type is reported as null:

```json
{
"name": "publishDate",
"type": null,
"mandatory": true
}
```

@atomashpolskiy

**Comment by atomashpolskiy** [comment]
Types encoding is done in `com.nhl.link.rest.encoder.PropertyMetadataEncoder#getPropertyType`. We probably shouldn't render Java8 date-time types as `date`, because it's misleading and because we won't be able to parse a conventional date in all cases. In fact, I now think that it would be better to not translate types into a JS-like simplistic type system, but rather specify Java FQCN. Even more so with LR client and java-to-java integration. What do you think?

**Comment by andrus** [comment]
Yeah I get the concern about dumb JSON type system. Though I am not comfortable with using Java FQNs either. We shouldn't leak anything Java-specific. 

So perhaps we follow Swagger and specify the JSON type, but add a secondary qualifier (called "format" in Swagger). See "Data Types" under http://swagger.io/specification/ ).

**Comment by atomashpolskiy** [comment]
Seems fine. Per RFC3339 we'll end up with the following metatypes:
LocalDate: type: date, format: full-date
LocalDateTime: type: date, format: date-time
LocalTime: type: date, format: full-time

**Comment by atomashpolskiy** [comment]
fixed
