### ISSUE TITLE
Error reading relationships: Multi-join relationship propagation is not supported yet

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#234]
In 2.5 we started seeing errors like `Multi-join relationship propagation is not supported yet: XyzEntity`. This looks like a regression introduced in 9db15c25e5e7, 312a917800a7 and friends. It looks like a very specific place (related to update processing and sencha adapter) got propagated to the top level and now affects entity compiler. This broke a read-only app trying to cross multi-join relationships. 

Since I need a quick patch, I am going to remove this check completely. But we may need to readd it back to entity traverser or elsewhere in the right scope. @atomashpolskiy

**Comment by atomashpolskiy** [comment]
As far as my understanding goes, this check is for the case when some attribute in the update is a relationship and the underlying DbRelationship's FK is also a PK of the root entity. It checks that the FK is not multi-column, because only one value is provided in the update request.
This check first appeared in UpdateParser (named DataObjectProcessor back then): [2bc0dbb9](https://github.com/nhl/link-rest/commit/2bc0dbb97b7d56497b3688613fa5c8c10107f2b4#diff-93fd63c2fdaa05287ebc8d553dd2a9aaR122) and later was moved to EntityJsonTraverser: [8d905ac7](https://github.com/nhl/link-rest/commit/8d905ac7ac0270bfd23cbf00e87c95c8a76c1996#diff-a2b24b9b86f47277b724a6a35ccef5bbR99). This is indeed a pretty specific case, but it's not related to Sencha at all. The real problem seems to be that prior to latest refactoring this check was performed only when the relationship in question appeared in the update request, and now it's performed for all entity relationships during compilation of the entity.

**Comment by andrus** [comment]
Correct. Its scope got expanded.

**Comment by atomashpolskiy** [comment]
On the other hand, Cayenne's scope got reduced. Dialectics..
