### ISSUE TITLE
UpdateBuilder: passing int ID where an implicit ID is long 

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#90]
Presumably this was fixed long time ago per #55, but there are reports that it is still a problem in some situations. E.g. here is a very simple update chain:

```
   linkRestService.update(Entity.class).id(id).uri(uriInfo).includeData().process(data);
```
Entity's implicit ID is Long. If int is passed here, it results in an error like "500 Internal Server Error (Invalid key item: {id=1})"

**Comment by atomashpolskiy** [comment]
This is because in Normalizer there's only one helper instance registered, and that's for java.lang.Long type. Lookup for normalizer helper is done based on DB primary key type, and the value being normalized is source key (by source I mean entity in the request). If it's Integer and PK type is BIGINT, then it's widened to Long, otherwise it's returned as is. The missing case (and the cause of error) is when PK type is INT and source key type is Long (at least on the REST method signature level); eventually the source key is placed into the key-update map as-is (i.e. as Long). After that, for each entity updates are taken from this map by entity key, which was once created by Cayenne, and obviously that's Integer wrapped in Map.

**Comment by atomashpolskiy** [comment]
Source -> DB
int -> int - OK
int -> long - OK
long -> long - OK
long -> int - NOT OK (and probably should not be?)

**Comment by andrus** [comment]
Yes, you are right. The description of the issue is wrong. This really is the case of long -> int conversion, which should not be allowed. So this is a user error.
